<h1>Object Detection</h1>
<h2>Importing the libraries</h2>

In [2]:
import cv2 
import numpy as np

In [ ]:
def displayImage(image, text):
    cv2.imshow(text, image)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

<h2>Loading the model</h2>

In [7]:
net = cv2.dnn.readNetFromCaffe('deploy.prototxt.txt', 'res10_300x300_ssd_iter_140000.caffemodel')
image = cv2.imread('./iron_chic.jpg')
(h,w) = image.shape[:2]
#Creating a blob from the image
blob = cv2.dnn.blobFromImage(cv2.resize(image, (300,300)), 1.0, (300, 300), (104.0, 177.0, 123.0))

<h2>Detecting Faces</h2>

In [16]:
net.setInput(blob)
detections = net.forward()

for i in range(0, detections.shape[2]):
    confidence = detections[0, 0, i, 2] # confidence of the prediction
    if confidence > 0.5: #
        box = detections[0, 0, i, 3:7] * np.array([w, h, w, h]) #getting the x-y coordinates of the bounding box
        (startX, startY, endX, endY) = box.astype("int")
        text = "{:.2f}%".format(confidence*100)
        #drawing the bounding box and the confidence of the prediction
        y = startY - 10 if startY - 10 > 10 else startY+10
        cv2.rectangle(image, (startX, startY), (endX, endY), (0,0,255), 2)
        cv2.putText(image, text, (startX, y), cv2.FONT_HERSHEY_SIMPLEX, 0.45, (0,0,255), 2)

displayImage(iamge, 'Intial Dectetions')

[500 500 500 500]
[500 500 500 500]
[500 500 500 500]
